version: 1
frontend:
  phases:
    preBuild:
      commands:
        - echo Installing dependencies...
        - npm install
    build:
      commands:
        - echo Building React app...
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*